framework:
    cache:
        # Unique name of your apps: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "apps" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #apps: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #apps: cache.adapter.apcu

        # Namespaced pools use the above "apps" backend by default
        #pools:
            #my.dedicated.cache: null
