# App Security — puerto 8000
server {
    listen 8000;
    root /var/www/html/apps/security/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/apps/security/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/apps/security/public;
        fastcgi_read_timeout 120;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}

# App Core — puerto 8001
server {
    listen 8001;
    root /var/www/html/apps/core/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/apps/core/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/apps/core/public;
        fastcgi_read_timeout 120;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
